name: Post to Repository A

# The 'on' block and its children must be indented correctly
on:
  push:
    paths:
      - '**.md'
      - 'postmap.json'

jobs:
  post-to-A:
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: saneume-ti/dev-post-target # ★ A のリポジトリ
      # The GH_TOKEN is used by the 'git clone' and 'gh pr create' commands
      GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_A }}

    steps:
      # Each step under 'steps:' is a list item, denoted by a hyphen '-'
      - name: Checkout B repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

#      - name: Install GitHub CLI
#        uses: cli/cli-action@v2
        # No 'with' block is needed here because the GH_TOKEN is already set
        # in the job's environment variables, and the CLI will use it automatically.

      - name: Clone A repository
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git a-repo

      - name: Inject content to A repository based on postmap.json
        run: |
          mapfile -t entries < <(jq -c '.[]' postmap.json)
          for entry in "${entries[@]}"; do
            src=$(echo "$entry" | jq -r '.source')
            dst=$(echo "$entry" | jq -r '.target')
            src_content=$(cat "$src")

            dst_path="a-repo/$dst"
            if [[ ! -f "$dst_path" ]]; then
              echo "Warning: Target file $dst_path not found"
              continue
            fi

            # Using a temporary file is a safe way to edit files in place
            awk -v insert="$src_content" '
              BEGIN {f=0}
              # Recommendation: remove the space in your markdown markers for consistency
              # e.g., change [] (posting-begin) to [](posting-begin)
              /^\[\]\(posting-begin\)/ {
                print
                print insert
                f=1
                next
              }
              /^\[\]\(posting-end\)/ {
                f=0
                print
                next
              }
              !f {print}
            ' "$dst_path" > "$dst_path.tmp" && mv "$dst_path.tmp" "$dst_path"

            echo "Updated $dst_path"
          done

      - name: Commit and push changes
        run: |
          cd a-repo
          git checkout -b auto/posting-update
          git add .
          # This command commits only if there are staged changes
          git diff --cached --quiet || git commit -m "Auto-update from B repo"
          git push -u origin auto/posting-update --force

      - name: Create Pull Request
        run: |
          cd a-repo
          # Check if a PR with the same head branch already exists
          existing_pr=$(gh pr list --head auto/posting-update --json number --jq '.[0].number')
          if [[ -n "$existing_pr" ]]; then
            echo "A PR from auto/posting-update already exists. (#${existing_pr})"
          else
            # Create a new PR
            gh pr create \
              --repo ${TARGET_REPO} \
              --title "Auto update from B repo" \
              --body "This PR contains automated content update from B" \
              --head auto/posting-update \
              --base main
          fi
